### ISSUE TITLE
사용자가 입력하는 값에 중복 숫자 입력 가능 여부

### ISSUE THREAD

**Issue by codingonwave** [next-step/java-baseball-precourse#560]
안녕하세요.

사용자가 입력한 3자리 숫자 중 중복되는 숫자가 있는 경우 잘못된 입력으로 봐야할지 문의드립니다.

예시)
사용자입력: 113

**Comment by ungseokchoi** [comment]
공유해주신 기능 요구서 pdf 부분에 보시면
"기본적으로 1부터 9까지 서로 다른 수로 이루어진 3자리의 수를 맞추는 게임이다." 라고 명시 되어있네요.

**Comment by hyeok7777** [comment]
서로 다른 숫자로 이루어진 세자리의 숫자를 맞추는 게임이기 때문에 잘못 된 입력으로 처리하는게 맞다고 생각합니다!

**Comment by codingonwave** [comment]
코멘트 감사합니다!
